### PR TITLE
Fix for null value for numeric

### PR DESCRIPTION
**Pull request by alfred-b-chan**
if it's null, output period instead of underscore for numeric.  i ran the pytest (test_v56.py) and they all passed.

### CODE REVIEW

**Comment by selik** [comment]
Thanks, I'll take a look this week.

**Comment by alfred-b-chan** [comment]
hey.. any update?

**Comment by selik** [comment]
Looks good to me. The only issue is updating the project version number!

Do you mind updating the version number in `setup.cfg` to `version = 3.2.2`? PyPI requires all code changes to be accompanied by a version number change.

Also, you can take credit for the change by noting something in CHANGELOG.rst or at the bottom of README.rst, in the authors section.

**Comment by selik** [comment]
Also, sorry for the delay.

**Comment by alfred-b-chan** [comment]
done, pls check

**Review by selik — APPROVED** [review]
LGTM

**Comment by selik** [comment]
I don't have an automated push to PyPI, so I'll need to handle that separately.

**Comment by damon-dirocco** [comment]
Hello Michael, I'm a colleague of Alfred.  I just wanted to say this utility/library that you've built has be a great help to our team.  We have a strong appreciation for users in this community such as yourself considering this is all done on your own personal time.  I am reaching to first thank you and second to ask if this change has been pushed or if could be pushed if at all possible.  Thanks for all your help!

**Comment by selik** [comment]
Hi @damon-dirocco Thanks for reminding me. I pulled the latest version and the unit tests are failing, so I'll need to debug.

**Comment by selik** [comment]
@damon-dirocco @alfred-b-chan When you run `make check` on xport v3.2.2 do you get unit test errors?

**Comment by alfred-b-chan** [comment]
ran all unit tests (within test folder) without an issue..  for the make check.. can't seem to run.. pls gimme instruction

**Comment by selik** [comment]
You should be able to run `make check` from the root folder of the repository. Same location as the `Makefile` file. I'm getting unit test failures, maybe because I'm on Ubuntu at the moment.

**Comment by alfred-b-chan** [comment]
windows is not supported for this library based upon what i read from makefile.   and i got my ubuntu vm running and saw those 7 issues.   hmm. those issues don't seem to be new (prior my update).  this proj doesn't seem to have an abundant source of setup/config (for debug).. .. can u gimme some instructions on localhost setup?  so i can debug and contribute even more to this open source library

**Comment by selik** [comment]
@alfred-b-chan I'd been developing on MacOS. The instructions in the Contributing section of the README (https://github.com/selik/xport#contributing) should set up an isolated Conda environment for work on the xport project.

**Comment by selik** [comment]
Oh, and Windows isn't *not* supported, but one would need the `make` command to take advantage of the `Makefile` for configuring a dev environment. Powershell, git-bash, or the Windows Subsystem for Linux would make it easier.

**Comment by damon-dirocco** [comment]
@selik and @alfred-b-chan, appreciate the effort on this.  just curious if there's much more to do here or if we're close to finalizing?  and if we're close, is it possible to close it today?  don't want to be pushy with this, but it will be a significant step forward on our side.  Thanks!

**Comment by selik** [comment]
@damon-dirocco Yeah, there's a bit of research I'll need to do to figure out what's different between my old setup where tests passed and my new dev environment, where the tests are failing. In the meantime, I'm not sure why you need the code on PyPI. It's handy for others, of course, but you could simply clone the version you want from GitHub instead of `pip install xport`. Pip supports installing from GitHub, and even allows specifying a particular commit.

**Pull request merged**
